#eureka.client.registerWithEureka = false
#eureka.client.fetchRegistry = false
#eureka.client.healthcheck.enabled = true
server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true