#eureka.client.registerWithEureka = false
#eureka.client.fetchRegistry = false
#eureka.client.healthcheck.enabled = true
server:
  port: 8761

eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    healthcheck:
      enabled: true