server:
  port: 8082

spring:
  application:
    name: troops

#eureka.instance.preferIpAddress=true
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
#eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}