server:
  port: 8080

spring:
  application:
    name: soldier

eureka:
  #  instance:
  #    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
#      serviceUrl:
#        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
