server:
  port: 8081

spring:
  application:
    name: soldier

#eureka.instance.preferIpAddress=true
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
#eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}