server:
  port: 8080

spring:
  application:
    name: soldier

eureka:
  #  instance:
  #    preferIpAddress: true
  client:
    instance:
      hostname: gateway
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery:8761/eureka}
