server:
  port: 8090

spring:
  application:
    name: zuul-server

ribbon:
  eureka:
    enabled: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

#not need if user service name as root /serviceName
#zuul.routes.soldier.path=/proxySoldier/**

#not need since match with service name
#zuul.routes.soldier.serviceId=soldier

#not need due to usage of eureka
#zuul.routes.soldier.url=http://localhost:8081

#zuul.routes.troops.path=/proxyTroops/**

zuul:
  routes:
    soldier:
      url: http://localhost:8081
      serviceId: soldier
#      path: /proxySoldier/**
    troops:
      url: http://localhost:8082
      serviceId: troops
#      path: /proxyTroops/**