server:
  port: 8090

spring:
  application:
    name: zuul-server
  cloud:
    config:
      uri: http://localhost:9999

ribbon:
  eureka:
    enabled: true

#not need with discovery
#zuul:
#  routes:
#    soldier:
#      #not need since match with service name
#      serviceId: soldier
#      #not need due to usage of eureka
#      url: http://localhost:8081
#      #not need if user service name as root /serviceName
#      path: /proxySoldier/**
#    troops:
#      serviceId: troops
#      url: http://localhost:8082
#      path: /proxyTroops/**
